### ISSUE TITLE
Whitespace in rules

### ISSUE THREAD

**Issue by vladkazantsev** [nbs-system/naxsi#218]
Hi, is there any way to match white space or wild characters in rules, using either  rx: or str: syntax? I.e. I don't need to match just "insert" but need to match "insert into" for mysql rules. Happy to use str syntax but obviously getting rx to work will be even better. Neither rx nor str seem to be able to match white space. I think best would be to match any number of any characters in between the "insert" and "into" - as long as the two are in the same post variable.

After a bit of investigation, this valid regex pattern does not work:
`delete[\s]+from` and neither does `delete([\s]+)from` when used for rx syntax. It seems like () characters are not recognized at all.

**Comment by buixor** [comment]
Hi !

I tried like this :
 MainRule "rx:delete([\s]+)from"  "msg:text RX" "mz:ARGS|URL|BODY|$HEADERS_VAR:Cookie" "s:DROP" id:1319;

and it works for me, I think you forgot to quote or something.


On a side note, if this is to detect SQLi, that's a bad idea, because :

del/**/ete from
delete/**/     from
delete/**/ /**/fr/**/om

are valid forms as well, and there are many other possible variations.
