### ISSUE TITLE
Enable in named location

### ISSUE THREAD

**Issue by vladimir000** [nbs-system/naxsi#303]
Hello,

We are trying to enable/disable naxsi based on specific parameters like specific cookies and combinations of conditions and variables set earlier, so we'd need to enable it in @named location but we see that naxsi parameters in named location are ignored.

For example:

```
location / {
error_page 450 = @on;
error_page 451 = @off;
if ( complex stuff here.. or even a combination of many variables and conditions with many "if" even if "if" is evil)
   return 451;
}
return 450;
}
location @on {
SecRulesEnabled; # ignored
}
location @off {
BasicRule wl:0 # ignored
SecRulesDisabled; # ignored
LearningMode; # ignored
#!@#
}

```

Will it change? Is it because it works in REWRITE?

Would it work to allow to enable/disable naxsi with:

SecRules on;
And allow variables instead of "on".

I know it would be more complex to allow this for BasicRule directives, but what about allowing it for on/off at least. So we could set a variable in http {} using map with all the conditions we want.

Or allowing SecRulesDisabled / Enabled in if(), (and possibly BasicRule too), possible?

Or is there any other possibility to have different naxsi settings in different named locations?
I know there are naxsi settings to use whitelisting but sometimes we need complex configurations that can't be specified with it.

**Comment by buixor** [comment]
Hello,

I never came accross this issue, and there shouldn't be a difference between named locations and normal locations imho. However, due to the return (which I think actually triggers an internal redirect) naxsi might ignore this, because it explictely avoid treating internal redirected requests (because of some specific cases we came accross in the past).

Right now I don't have any appropriate suggestion to give, but dynamic modifiers might help. They do work at http {} level (https://github.com/buixor/naxsi/wiki/runtime-modifiers)

```
http {
if (randomstuff) { set $naxsi_flag_enable 1; }
location / {
}
```

Please let me know :)

**Comment by vladimir000** [comment]
Hello!

This is THE solution. I solved my problem thanks!
Still not perfect as we can't customize, just turn off/on, but in my case it is enough.
Hope it helps someone as searching for "naxsi" + "named location" wasn't returning anything useful.

Thanks a lot

**Comment by buixor** [comment]
It might be something we think about in the future, but right now I can't evaluate the implications :)
