### ISSUE TITLE
Unblock rule 2 for some requests

### ISSUE THREAD

**Issue by Peter2121** [nbs-system/naxsi#328]
I'm trying to add whitelist rule for some ActiveSync requests.
Now my requests are blocked as follows:

```
2016/12/02 14:51:18 [error] 75640#0: *38 NAXSI_FMT: ip=000.000.000.000&server=xxx.xxx.xxx&uri=/Microsoft-Server-ActiveSync&learning=0&vers=0.54&total_processed=13&total_blocked=3&block=1&zone0=BODY&id0=2&var_name0=, client: 000.000.000.000, server: xxx.xxx.xxx, request: "POST /Microsoft-Server-ActiveSync?User=xxx.xxx@xxx.xxx&DeviceId=XXXXXXXXXXX&DeviceType=iPhone&Cmd=SendMail HTTP/1.1", host: "xxx.xxx.xxx"
```

It is normal as I'm trying to send a mail with an attached file.
Following the docs of NAXSI, I added a whitelist:

```
BasicRule  wl:2 "mz:$URL_X:SendMail|BODY" ;
```
But it's still blocked.
I tried with:

```
BasicRule  wl:2 "mz:$BODY_VAR_X:SendMail|BODY" ;
```
Idem.

Is there something I missed or it's a NAXSI bug?

**Comment by buixor** [comment]
Hello,

You need to make your rules lowercase, like :

```
BasicRule wl:2 "mz:$URL:/microsoft-server-activesync|BODY" ;
```

Can you confirm if it's working ?

**Comment by Peter2121** [comment]
If I understand the syntax, it will disable rule 2 for the whole site /microsoft-server-activesync. 
This is definitely NOT my aim, I would like to disable rule 2 just for POST with Cmd=SendMail present in arguments only.

**Comment by buixor** [comment]
Hello,

Rule 2 is this : https://github.com/nbs-system/naxsi/wiki/internal-rules#big_request

means it applies to the whole body (body is too big, nginx decides to buffer it on disk), it makes little sense to apply it to **one** post variable :)

Thus you need to disable for a full uri at least.

Is it more clear like this ?

**Comment by Peter2121** [comment]
Mmm, it seems that I'm trying to configure an impossible white list rule.
The logic was "if Cmd=SendMail is present in POST - disable rule 2 for the BODY".
So, I cannot disable the check of the WHOLE body, putting the WL trigger on ONE post variable?
Maybe I can bypass NAXSI completely for this case (or use another NAXSI WL set), using NGINX regex filters on location level?

**Comment by buixor** [comment]
Hello,

I think this is quite a dangerous idea, bear with me :
 * Rule 2 fully disable naxsi when whitelisted on a specific scope (as the body is not parsed while stored on the disk)
 * Attackers add "Cmd=SendMail" in body, adds a lot of padding to bypass (to overflow "client_body_buffer_size" and thus bypass the WAF)
 * Profit

I don't know how big is the body, but you can increase "client_body_buffer_size" to be big enough so that it doesn't trigger the rule n° 2. On the other hand, I think it's a lot less dangerous to whitelist rule n°2 on a specific url.

If you can provide more details, maybe we can find a smarter work-around ?

Cheers,

**Comment by Peter2121** [comment]
I can't provide rather more details than I've put to the first message. It's a reverse-proxy to protect MS Exchange, it blocks actually any mail sent with an attachment using ActiveSync protocol. The attachment size can be really huge (10+MB), so I don't think that increasing client_body_buffer_size can help. I understand that bypassing rule 2 (in general) is a bad idea, that's why I'm trying to minimize the attack surface. If we must choose between disabling rule 2 in general and disabling rule 2 for some requests - I would prefer to disable it for some requests. We cannot filter a specific URL as in the MS logic ALL the work is doing in /Microsoft-Server-ActiveSync, so we should filter on request parameters, not on URL.

**Comment by buixor** [comment]
Mh I understand, and I'm afraid you hit a roadblock :
 * We can do some nasty tricks using (https://github.com/nbs-system/naxsi/wiki/olds-dynamicmodifiers) to disable naxsi at runtime if some specific criterias are met : Unfortunately, this would probably be a performance killer, because it implies that nginx will live parse a lot of data.
 * The initial suggested solution doesn't seem satisfying in your usage neither.

I'm going to think a bit about it, but I don't see any satisfying solution right now. Any reasonable discussion might rely on the capacity of naxsi to parse buffered files on the disk, solution that is not ready yet :/

**Comment by Peter2121** [comment]
OK, I'll try to use dynamicmodifiers, don't think that the performance matters in our case.
Hope to see more elegant solution later ;)
Thank you!

**Comment by buixor** [comment]
Please let me know what solution you end up with, it might be useful to others ;)
