### ISSUE TITLE
Creating White list Rules

### ISSUE THREAD

**Issue by tjosm** [nbs-system/naxsi#470]
I need help with a white list rule. I use nxutil to generate my wl rules, but ran into a small trouble with it. The generated rules are working but I know they can be better. Following are the rules nxutil suggested.

`BasicRule wl:1310,1311 "mz:$URL:/product/advanced-vps-security/|$BODY_VAR:addon-8294-extras-0[]|NAME";`
`BasicRule wl:1310,1311 "mz:$URL:/product/mail-server-setup/|$BODY_VAR:addon-8288-mail-server-extras-0[]|NAME";`
`BasicRule wl:1310,1311 "mz:$URL:/product/instal-sentrifugo-service/|$BODY_VAR:addon-7648-sentrifugo-extras-0[]|NAME";
`

I know I can get rid of $URL part and it'll still work. But what I prefer is to have a single rule to catch all of these. I'm not sure how to go about this.

Thanks in advance!

**Comment by he2ss** [comment]
Hi,

You can whitelist those IDs (`1310=[ 1311=]`) with a single rule but little bit more permissive but not rsiky because of those IDs, don't use this kind of whitelisting on ID 1000 for example.
Here is a solution : 

`BasicRule wl:1310,1311 "mz:$URL_X:^/product/[a-z\-]+/$|$BODY_VAR_X:^addon[a-z0-9\-]+\[\]$|NAME";`

**Comment by tjosm** [comment]
Thanks @he2ss. Really appreciate your help. This solved my problem.

However, I would also like to learn to write these rules myself. Do you have a suggestion as to where I should start?

Thanks

**Comment by he2ss** [comment]
Nice !
Yes, you can read the wiki and especially : https://github.com/nbs-system/naxsi/wiki/whitelists-bnf
