### ISSUE TITLE
Parenthesis in cookies

### ISSUE THREAD

**Issue by vcr-j** [nbs-system/naxsi#576]
Naxsi core rules block open and close parenthesis in cookies.
According to rfc 6265 a cookie value is:

```
 cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
 cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash
```
Could you allow parenthesis in Cookies i.e. remove $HEADERS_VAR:Cookie from rules 1010 and 1011 ?

Looks like hash (rules 1016), ampersand (rules 1006), hyphen (rules 1007), double dot (rules 1200), open and close square bracket (rules 1310 and 1311) and tilde (rules 1312)  should also be allowed but I didn't had the issue in production yet.

**Comment by wargio** [comment]
you can whitelist it.

**Comment by vcr-j** [comment]
Well I've already whitelisted it.
I'm just wondering what's the point of having default rules that are in contradiction with the RFC ?
It looks fairly common to have parenthesis in cookies, the RFC alllows it, so why are they blocked by the default config ?
I'm not aware of parenthesis in cookies being a security threat, if this is not the case it could be removed from the default config.

**Comment by wargio** [comment]
because there are a lot of vulnerabilities like SQL Injections that does use the cookies header.
the same question applies to the email format, which does allow some really weird patterns, but in reality nobody follows that RFC because it is too hard to validate it and parsing something so complex is indeed a problem and can be exploited.
Blocking the parenthesis is a normal thing in fields where you normally do not expect them.

**Comment by vcr-j** [comment]
Ok thanks for your answer.
