### ISSUE TITLE
WordPress Fruitful 3.8 Cross Site Scripting

### ISSUE THREAD

**Issue by sahrulfatih** [nbs-system/naxsi#621]
https://packetstormsecurity.com/files/156390/

what is the proper naxsi rule to solve this problem?

**Comment by wargio** [comment]
Given the fact that you have a very stupid XSS, there are multiple ways to break this and sort of block it, but normally the right route is to update the plugin.
that said what you probably want to do is to create a rule for the `comment` value in a `POST` request to forbid any `<` and `>` (note that you also need to block any UTF-8 chars that resembles to those symbols because some browsers does the normalization of the html code and would interpret [guillemets](https://en.wikipedia.org/wiki/Guillemet) as `<` and `>`)

An example what the rule could look like is this: 
```
MainRule "str:>" "msg:Fruitful XSS" "mz:$BODY_VAR:comment" "s:$UWA:8" id:1111111;
MainRule "str:<" "msg:Fruitful XSS" "mz:$BODY_VAR:comment" "s:$UWA:8" id:1111112;
```
