### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [nbs-system/naxsi#626]
I would like to point out that an identifier like “[`__NAXSI_H__`](https://github.com/nbs-system/naxsi/blob/d714f1636ea49a9a9f4f06dba14aee003e970834/naxsi_src/naxsi.h#L7 "Update candidate")” [does not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by wargio** [comment]
Absolutely i can fix this, but please do not use this repo but use (mine)[https://github.com/wargio/naxsi] and second, the code is C only since NGINX is written in C.
You definetely should not build it using a C++ compiler or it will complains about many other stuff.
There are not even the C guards for the code.
